### ISSUE TITLE
memory limits

### ISSUE THREAD

**Issue by MichelMoser** [bioinfologics/w2rap#5]
Hi, 

I repeatedly get memory overflow errors when setting -m option.
As it is a "soft" memory limit, as written in the options, is there an absolute way to limit memory requirements of w2rap?
I use a node of 256 Gb RAM and set -m 200 

Thank you, 
Michel

**Comment by jonwright99** [comment]
Hi Michel,

There's no hard limit option. We usually set the soft limit to ~80% of the hard limit but this doesn't ensure that the memory requirements don't break the hard limit. If you know which step is failing there are options you can use to reduce the memory usage in specific steps such as using disk batches for step 2 which stores kmer counts on disk rather than in memory. Alternatively, you can subsample reads to reduce memory requirements. What size genome are you trying to assemble and what read coverage are you using?

Best wishes,
Jon

**Comment by MichelMoser** [comment]
Hi Jon, 
Yes, its step 2 which is failing. I will try to use disk batches. The genome is in the 1.5 Gb range and coverage about 50x. 
Thanks, 
Michel

**Comment by jonwright99** [comment]
-d 8 or -d 16 on step 2 should do it

**Comment by MichelMoser** [comment]
thanks, it passed step 2
